### ISSUE TITLE
Support for multiple insecure registries

### ISSUE THREAD

**Issue by mwhahaha** [EmilienM/ansible-role-container-registry#1]
https://github.com/EmilienM/ansible-role-container-registry/blob/161e6adbc1f5cfe14f626c0f1011fddd600165a0/tasks/docker.yml#L42

**Comment by EmilienM** [comment]
this one is tricky, I might ask @samdoran how we can do a loop within inifile.
The idea is to have:

```
- name: configure INSECURE_REGISTRY in /etc/sysconfig/docker
  lineinfile:
    path: /etc/sysconfig/docker
    regexp: '^INSECURE_REGISTRY='
    line: "INSECURE_REGISTRY='--insecure-registry {{ insecure_registries }}'"
  when: insecure_registries != ""
  notify: restart docker service
```
Where insecure_registries is an array (example ['host1:port1', 'host2:port3']) and the line would be:
```
INSECURE_REGISTRY='--insecure-registry host1:port1 --insecure-registry host2:port2
```

Any idea if it's possible?

**Comment by samdoran** [comment]
You can do this with an inline Jinja expression.

I would also recommend setting the default value of `inscure_registries` to a list rather than a string to avoid issues with changing types. Keeping the variable one type will result in fewer Jinja headaches. 

```yaml
# defaults/main.yml
insecure_registries: []
```

And your task would look like this:

```yaml
- name: configure INSECURE_REGISTRY in /etc/sysconfig/docker
  lineinfile:
    path: /etc/sysconfig/docker
    regexp: '^INSECURE_REGISTRY='
    line: "INSECURE_REGISTRY='{{ registry_flags }}'"
  when: insecure_registries | length > 0
  notify: restart docker service
  vars:
    registry_flags: "{% for reg in insecure_registries %}--insecure-registry {{ reg }}{% if not loop.last %} {% endif %}{% endfor %}"
```
